# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setMinimumSize(QtCore.QSize(1200, 700))
        self.main.setToolTipDuration(-1)
        self.main.setStyleSheet("QFrame{\n"
"    border: 0px solid;\n"
"    background-color: #fff;\n"
"\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid rgb(18, 104, 255);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    padding: 0.5em;\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 104, 255);\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(19, 106, 255, 30%);\n"
"    border-style: inset;\n"
"}")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainbody = QtWidgets.QFrame(self.main)
        self.mainbody.setStyleSheet("QFrame{\n"
"color: #000\n"
"}")
        self.mainbody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbody.setObjectName("mainbody")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainbody)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.algos = QtWidgets.QFrame(self.mainbody)
        self.algos.setMinimumSize(QtCore.QSize(165, 0))
        self.algos.setMaximumSize(QtCore.QSize(165, 16777215))
        self.algos.setStyleSheet("QFrame{\n"
"background-color: rgb(226, 225, 232);\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0%);\n"
"border-radius:0px;\n"
"border:none;\n"
"border-right: 4px solid rgb(24, 112, 255);\n"
"color: rgba(0, 0, 0, 60%);\n"
"padding: 1.1em 0em;\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #fff;\n"
"}")
        self.algos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.algos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.algos.setLineWidth(1)
        self.algos.setObjectName("algos")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.algos)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.algos_graph = QtWidgets.QFrame(self.algos)
        self.algos_graph.setStyleSheet("")
        self.algos_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.algos_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.algos_graph.setObjectName("algos_graph")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.algos_graph)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bellmanford = QtWidgets.QPushButton(self.algos_graph)
        self.bellmanford.setMinimumSize(QtCore.QSize(0, 30))
        self.bellmanford.setObjectName("bellmanford")
        self.verticalLayout_2.addWidget(self.bellmanford)
        self.floydwarchal = QtWidgets.QPushButton(self.algos_graph)
        self.floydwarchal.setMinimumSize(QtCore.QSize(0, 30))
        self.floydwarchal.setObjectName("floydwarchal")
        self.verticalLayout_2.addWidget(self.floydwarchal)
        self.belmanfordmoore = QtWidgets.QPushButton(self.algos_graph)
        self.belmanfordmoore.setMinimumSize(QtCore.QSize(0, 30))
        self.belmanfordmoore.setObjectName("belmanfordmoore")
        self.verticalLayout_2.addWidget(self.belmanfordmoore)
        self.fordfulkerson = QtWidgets.QPushButton(self.algos_graph)
        self.fordfulkerson.setMinimumSize(QtCore.QSize(0, 30))
        self.fordfulkerson.setObjectName("fordfulkerson")
        self.verticalLayout_2.addWidget(self.fordfulkerson)
        self.kraskal = QtWidgets.QPushButton(self.algos_graph)
        self.kraskal.setMinimumSize(QtCore.QSize(0, 30))
        self.kraskal.setObjectName("kraskal")
        self.verticalLayout_2.addWidget(self.kraskal)
        self.astar = QtWidgets.QPushButton(self.algos_graph)
        self.astar.setMinimumSize(QtCore.QSize(0, 30))
        self.astar.setObjectName("astar")
        self.verticalLayout_2.addWidget(self.astar)
        self.bfs = QtWidgets.QPushButton(self.algos_graph)
        self.bfs.setMinimumSize(QtCore.QSize(0, 30))
        self.bfs.setObjectName("bfs")
        self.verticalLayout_2.addWidget(self.bfs)
        self.dfs = QtWidgets.QPushButton(self.algos_graph)
        self.dfs.setMinimumSize(QtCore.QSize(0, 30))
        self.dfs.setObjectName("dfs")
        self.verticalLayout_2.addWidget(self.dfs)
        self.verticalLayout_6.addWidget(self.algos_graph, 0, QtCore.Qt.AlignTop)
        self.algos_arbre = QtWidgets.QFrame(self.algos)
        self.algos_arbre.setStyleSheet("")
        self.algos_arbre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.algos_arbre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.algos_arbre.setObjectName("algos_arbre")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.algos_arbre)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.prefixe = QtWidgets.QPushButton(self.algos_arbre)
        self.prefixe.setMinimumSize(QtCore.QSize(0, 30))
        self.prefixe.setObjectName("prefixe")
        self.verticalLayout.addWidget(self.prefixe)
        self.infixe = QtWidgets.QPushButton(self.algos_arbre)
        self.infixe.setMinimumSize(QtCore.QSize(0, 30))
        self.infixe.setObjectName("infixe")
        self.verticalLayout.addWidget(self.infixe)
        self.postfixe = QtWidgets.QPushButton(self.algos_arbre)
        self.postfixe.setMinimumSize(QtCore.QSize(0, 30))
        self.postfixe.setObjectName("postfixe")
        self.verticalLayout.addWidget(self.postfixe)
        self.largeur = QtWidgets.QPushButton(self.algos_arbre)
        self.largeur.setMinimumSize(QtCore.QSize(0, 30))
        self.largeur.setObjectName("largeur")
        self.verticalLayout.addWidget(self.largeur)
        self.profondeur = QtWidgets.QPushButton(self.algos_arbre)
        self.profondeur.setMinimumSize(QtCore.QSize(0, 30))
        self.profondeur.setObjectName("profondeur")
        self.verticalLayout.addWidget(self.profondeur)
        self.verticalLayout_6.addWidget(self.algos_arbre, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.algos)
        self.show = QtWidgets.QFrame(self.mainbody)
        self.show.setStyleSheet("")
        self.show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show.setObjectName("show")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.show)
        self.verticalLayout_4.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.generate = QtWidgets.QFrame(self.show)
        self.generate.setMinimumSize(QtCore.QSize(0, 80))
        self.generate.setMaximumSize(QtCore.QSize(16777215, 80))
        self.generate.setStyleSheet("")
        self.generate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.generate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generate.setObjectName("generate")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.generate)
        self.horizontalLayout_4.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_algo_name = QtWidgets.QFrame(self.generate)
        self.frame_algo_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_algo_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_algo_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_algo_name.setObjectName("frame_algo_name")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_algo_name)
        self.horizontalLayout_8.setContentsMargins(0, 17, 0, 16)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textEdit = QtWidgets.QTextEdit(self.frame_algo_name)
        self.textEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_8.addWidget(self.textEdit)
        self.algorithm_name = QtWidgets.QTextEdit(self.frame_algo_name)
        self.algorithm_name.setMinimumSize(QtCore.QSize(230, 0))
        self.algorithm_name.setObjectName("algorithm_name")
        self.horizontalLayout_8.addWidget(self.algorithm_name)
        self.horizontalLayout_4.addWidget(self.frame_algo_name)
        self.frame_2 = QtWidgets.QFrame(self.generate)
        self.frame_2.setMinimumSize(QtCore.QSize(550, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.arbre_btn = QtWidgets.QPushButton(self.frame_2)
        self.arbre_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.arbre_btn.setStyleSheet("")
        self.arbre_btn.setAutoDefault(False)
        self.arbre_btn.setObjectName("arbre_btn")
        self.horizontalLayout_5.addWidget(self.arbre_btn)
        self.graph_btn = QtWidgets.QPushButton(self.frame_2)
        self.graph_btn.setStyleSheet("")
        self.graph_btn.setObjectName("graph_btn")
        self.horizontalLayout_5.addWidget(self.graph_btn)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.generate)
        self.drawing = QtWidgets.QFrame(self.show)
        self.drawing.setStyleSheet("")
        self.drawing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drawing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drawing.setObjectName("drawing")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.drawing)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InitFig = InitFig(self.drawing)
        self.InitFig.setMaximumSize(QtCore.QSize(100000, 100000))
        self.InitFig.setStyleSheet("border:1px solid")
        self.InitFig.setObjectName("InitFig")
        self.horizontalLayout_2.addWidget(self.InitFig)
        self.ResultFig = ResultFig(self.drawing)
        self.ResultFig.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.ResultFig.setStyleSheet("border: 1px solid")
        self.ResultFig.setObjectName("ResultFig")
        self.horizontalLayout_2.addWidget(self.ResultFig)
        self.verticalLayout_4.addWidget(self.drawing)
        self.applay = QtWidgets.QFrame(self.show)
        self.applay.setMaximumSize(QtCore.QSize(16777215, 80))
        self.applay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.applay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.applay.setObjectName("applay")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.applay)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.generate_frame = QtWidgets.QFrame(self.applay)
        self.generate_frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.generate_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.generate_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.generate_frame.setObjectName("generate_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.generate_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.generate_frame)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.nb_nodes = QtWidgets.QSpinBox(self.generate_frame)
        self.nb_nodes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nb_nodes.setObjectName("nb_nodes")
        self.horizontalLayout_6.addWidget(self.nb_nodes)
        self.generate_btn = QtWidgets.QPushButton(self.generate_frame)
        self.generate_btn.setObjectName("generate_btn")
        self.horizontalLayout_6.addWidget(self.generate_btn)
        self.horizontalLayout_7.addWidget(self.generate_frame)
        self.frame = QtWidgets.QFrame(self.applay)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.start_label = QtWidgets.QLabel(self.frame)
        self.start_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start_label.setToolTip("")
        self.start_label.setObjectName("start_label")
        self.horizontalLayout_9.addWidget(self.start_label)
        self.start_node = QtWidgets.QSpinBox(self.frame)
        self.start_node.setMaximumSize(QtCore.QSize(75, 16777215))
        self.start_node.setObjectName("start_node")
        self.horizontalLayout_9.addWidget(self.start_node)
        self.but_label = QtWidgets.QLabel(self.frame)
        self.but_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.but_label.setObjectName("but_label")
        self.horizontalLayout_9.addWidget(self.but_label)
        self.but_node = QtWidgets.QSpinBox(self.frame)
        self.but_node.setMaximumSize(QtCore.QSize(75, 16777215))
        self.but_node.setObjectName("but_node")
        self.horizontalLayout_9.addWidget(self.but_node)
        self.apply_btn = QtWidgets.QPushButton(self.frame)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout_9.addWidget(self.apply_btn)
        self.horizontalLayout_7.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.applay)
        self.horizontalLayout.addWidget(self.show)
        self.verticalLayout_5.addWidget(self.mainbody)
        self.gridLayout.addWidget(self.main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bellmanford.setText(_translate("MainWindow", "Bellman-Ford"))
        self.floydwarchal.setText(_translate("MainWindow", "Floyd-Warchal"))
        self.belmanfordmoore.setText(_translate("MainWindow", "Bellman-ford-Moore"))
        self.fordfulkerson.setText(_translate("MainWindow", "Ford Fulkerson"))
        self.kraskal.setText(_translate("MainWindow", "Kruskal"))
        self.astar.setText(_translate("MainWindow", "A*"))
        self.bfs.setText(_translate("MainWindow", "BFS"))
        self.dfs.setText(_translate("MainWindow", "DFS"))
        self.prefixe.setText(_translate("MainWindow", "Prefixe n-air"))
        self.infixe.setText(_translate("MainWindow", "infixe n-air"))
        self.postfixe.setText(_translate("MainWindow", "postfixe n-air"))
        self.largeur.setText(_translate("MainWindow", "largeur n-air"))
        self.profondeur.setText(_translate("MainWindow", "profondeur n-air"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">currant algorithm: </span></p></body></html>"))
        self.algorithm_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.arbre_btn.setText(_translate("MainWindow", "Tree"))
        self.graph_btn.setText(_translate("MainWindow", "Graph"))
        self.label.setText(_translate("MainWindow", "nodes number:"))
        self.generate_btn.setText(_translate("MainWindow", "Generate"))
        self.start_label.setText(_translate("MainWindow", "Start:"))
        self.but_label.setText(_translate("MainWindow", "But:"))
        self.apply_btn.setText(_translate("MainWindow", "Apply"))
from interface.initfig import InitFig
from interface.resultfig import ResultFig


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
